"""Initial migration

Revision ID: 734b146b376d
Revises: 
Create Date: 2026-04-29 06:14:29.577173+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '734b146b376d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('idx_app_settings_key', 'app_settings', ['key'], unique=False)
    op.create_table('backup_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('current_step', sa.String(length=512), nullable=True),
    sa.Column('total_users', sa.Integer(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('matched', sa.Integer(), nullable=False),
    sa.Column('unmatched', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.String(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backup_jobs_created', 'backup_jobs', ['created_at'], unique=False)
    op.create_index('idx_backup_jobs_status', 'backup_jobs', ['status'], unique=False)
    op.create_index('idx_backup_jobs_type', 'backup_jobs', ['job_type'], unique=False)
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jellyfin_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_libraries_jellyfin_id', 'libraries', ['jellyfin_id'], unique=False)
    op.create_index('idx_libraries_name', 'libraries', ['name'], unique=False)
    op.create_index('idx_libraries_type', 'libraries', ['item_type'], unique=False)
    op.create_index(op.f('ix_libraries_jellyfin_id'), 'libraries', ['jellyfin_id'], unique=True)
    op.create_table('notifiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifiers_enabled', 'notifiers', ['enabled'], unique=False)
    op.create_index('idx_notifiers_type', 'notifiers', ['type'], unique=False)
    op.create_table('servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_servers_name', 'servers', ['name'], unique=False)
    op.create_index('idx_servers_url', 'servers', ['url'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jellyfin_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('total_plays', sa.Integer(), nullable=False),
    sa.Column('total_watch_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_jellyfin_id', 'users', ['jellyfin_id'], unique=False)
    op.create_index('idx_users_last_active', 'users', ['last_active'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_jellyfin_id'), 'users', ['jellyfin_id'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jellyfin_id', sa.String(length=255), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('sort_name', sa.String(length=512), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('premiere_date', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('community_rating', sa.Float(), nullable=True),
    sa.Column('official_rating', sa.String(length=50), nullable=True),
    sa.Column('runtime_ticks', sa.Integer(), nullable=True),
    sa.Column('genres', sa.String(length=1024), nullable=True),
    sa.Column('studios', sa.String(length=1024), nullable=True),
    sa.Column('poster_url', sa.String(length=512), nullable=True),
    sa.Column('backdrop_url', sa.String(length=512), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('external_ids', sa.String(length=1024), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_items_added', 'items', ['added_at'], unique=False)
    op.create_index('idx_items_jellyfin_id', 'items', ['jellyfin_id'], unique=False)
    op.create_index('idx_items_library', 'items', ['library_id'], unique=False)
    op.create_index('idx_items_series_id', 'items', ['series_id'], unique=False)
    op.create_index('idx_items_type', 'items', ['item_type'], unique=False)
    op.create_index('idx_items_year', 'items', ['year'], unique=False)
    op.create_index(op.f('ix_items_jellyfin_id'), 'items', ['jellyfin_id'], unique=True)
    op.create_table('notification_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notifier_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('filters', sa.String(), nullable=True),
    sa.Column('template', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notifier_id'], ['notifiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_rules_enabled', 'notification_rules', ['enabled'], unique=False)
    op.create_index('idx_notification_rules_event_type', 'notification_rules', ['event_type'], unique=False)
    op.create_index('idx_notification_rules_notifier', 'notification_rules', ['notifier_id'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(length=255), nullable=False),
    sa.Column('device', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_user_device')
    )
    op.create_index('idx_user_devices_device_id', 'user_devices', ['device_id'], unique=False)
    op.create_index('idx_user_devices_last_seen', 'user_devices', ['last_seen'], unique=False)
    op.create_index('idx_user_devices_user', 'user_devices', ['user_id'], unique=False)
    op.create_table('active_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jellyfin_session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('device', sa.String(length=255), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('video_codec', sa.String(length=50), nullable=True),
    sa.Column('audio_codec', sa.String(length=50), nullable=True),
    sa.Column('container', sa.String(length=50), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('transcode', sa.Boolean(), nullable=False),
    sa.Column('transcode_reason', sa.String(length=255), nullable=True),
    sa.Column('transcode_hw', sa.String(length=50), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('item_name', sa.String(length=512), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('series_name', sa.String(length=512), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('buffer_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jellyfin_session_id')
    )
    op.create_index('idx_active_sessions_jellyfin_id', 'active_sessions', ['jellyfin_session_id'], unique=False)
    op.create_index('idx_active_sessions_state', 'active_sessions', ['state'], unique=False)
    op.create_index('idx_active_sessions_user', 'active_sessions', ['user_id'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notifier_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error', sa.String(length=2048), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notifier_id'], ['notifiers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['notification_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_log_created', 'notification_log', ['created_at'], unique=False)
    op.create_index('idx_notification_log_event_type', 'notification_log', ['event_type'], unique=False)
    op.create_index('idx_notification_log_notifier', 'notification_log', ['notifier_id'], unique=False)
    op.create_index('idx_notification_log_status', 'notification_log', ['status'], unique=False)
    op.create_table('session_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jellyfin_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('paused_duration', sa.Integer(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('completion_pct', sa.Float(), nullable=True),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('device', sa.String(length=255), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('video_codec', sa.String(length=50), nullable=True),
    sa.Column('audio_codec', sa.String(length=50), nullable=True),
    sa.Column('container', sa.String(length=50), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('transcode', sa.Boolean(), nullable=False),
    sa.Column('transcode_reason', sa.String(length=255), nullable=True),
    sa.Column('transcode_hw', sa.String(length=50), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('item_name', sa.String(length=512), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('series_name', sa.String(length=512), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('playback_position_ticks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jellyfin_id')
    )
    op.create_index('idx_session_history_item', 'session_history', ['item_id'], unique=False)
    op.create_index('idx_session_history_library', 'session_history', ['library_id'], unique=False)
    op.create_index('idx_session_history_started', 'session_history', ['started_at'], unique=False)
    op.create_index('idx_session_history_user', 'session_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_session_history_started_at'), 'session_history', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_history_started_at'), table_name='session_history')
    op.drop_index('idx_session_history_user', table_name='session_history')
    op.drop_index('idx_session_history_started', table_name='session_history')
    op.drop_index('idx_session_history_library', table_name='session_history')
    op.drop_index('idx_session_history_item', table_name='session_history')
    op.drop_table('session_history')
    op.drop_index('idx_notification_log_status', table_name='notification_log')
    op.drop_index('idx_notification_log_notifier', table_name='notification_log')
    op.drop_index('idx_notification_log_event_type', table_name='notification_log')
    op.drop_index('idx_notification_log_created', table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index('idx_active_sessions_user', table_name='active_sessions')
    op.drop_index('idx_active_sessions_state', table_name='active_sessions')
    op.drop_index('idx_active_sessions_jellyfin_id', table_name='active_sessions')
    op.drop_table('active_sessions')
    op.drop_index('idx_user_devices_user', table_name='user_devices')
    op.drop_index('idx_user_devices_last_seen', table_name='user_devices')
    op.drop_index('idx_user_devices_device_id', table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index('idx_notification_rules_notifier', table_name='notification_rules')
    op.drop_index('idx_notification_rules_event_type', table_name='notification_rules')
    op.drop_index('idx_notification_rules_enabled', table_name='notification_rules')
    op.drop_table('notification_rules')
    op.drop_index(op.f('ix_items_jellyfin_id'), table_name='items')
    op.drop_index('idx_items_year', table_name='items')
    op.drop_index('idx_items_type', table_name='items')
    op.drop_index('idx_items_series_id', table_name='items')
    op.drop_index('idx_items_library', table_name='items')
    op.drop_index('idx_items_jellyfin_id', table_name='items')
    op.drop_index('idx_items_added', table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_users_jellyfin_id'), table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_last_active', table_name='users')
    op.drop_index('idx_users_jellyfin_id', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_servers_url', table_name='servers')
    op.drop_index('idx_servers_name', table_name='servers')
    op.drop_table('servers')
    op.drop_index('idx_notifiers_type', table_name='notifiers')
    op.drop_index('idx_notifiers_enabled', table_name='notifiers')
    op.drop_table('notifiers')
    op.drop_index(op.f('ix_libraries_jellyfin_id'), table_name='libraries')
    op.drop_index('idx_libraries_type', table_name='libraries')
    op.drop_index('idx_libraries_name', table_name='libraries')
    op.drop_index('idx_libraries_jellyfin_id', table_name='libraries')
    op.drop_table('libraries')
    op.drop_index('idx_backup_jobs_type', table_name='backup_jobs')
    op.drop_index('idx_backup_jobs_status', table_name='backup_jobs')
    op.drop_index('idx_backup_jobs_created', table_name='backup_jobs')
    op.drop_table('backup_jobs')
    op.drop_index('idx_app_settings_key', table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
